### ISSUE TITLE
Channel message backup

### ISSUE THREAD

**Issue by luizfx22** [iLuiizUHD/ExpertiseBotRewritten#3]
### TODO:
- [x] Create database structures
- [x] Command that add server and channels in database
- [x] Command that someone can set a log channel
- [ ] Auto insert channel in database when created
- [ ] Auto update channel information when updated
- [ ] Auto delete channel from database when deleted
- [ ] Auto warn when a channel is deleted
- [ ] Warn server owner when a channel is deleted and how he can restore it
